services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: litellm
      POSTGRES_USER: llmproxy
      POSTGRES_PASSWORD: dbpassword9090
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d litellm -U llmproxy"]
      interval: 1s
      timeout: 5s
      retries: 10

  litellm:
    build: .
    ports:
      - "4000:4000"
    volumes:
      # Mount config for easy model updates
      - ./config:/app/config:ro
      # Mount provider code for development
      - ./providers:/app/providers:ro
      # Persistent volume for Claude authentication
      - claude_auth:/root/.claude_code
      # Optional: Mount host auth as fallback (read-only)
      - ~/.claude_code:/root/.claude_code_host:ro
      - ~/.claude.json:/root/.claude.json_host:ro
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
  claude_auth: